# -*- coding: utf-8 -*-
"""backpropagation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KuCT2qocaNvd6a95AGf7yGOcJKgVSKd
"""

# Import Library
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

# Memuat data
data_training = pd.read_excel('data_scaled_train.xlsx')

# Memisahkan fitur input dan output
input_features = ['TN', 'TX', 'TAVG', 'RH_AVG', 'SS']
output_features = ['RR']

# Memisahkan data input dan output
X_train = data_training[input_features]
y_train = data_training[output_features]

model = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

hist = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=32,
    verbose=1
)

#  Membuat diagram error
model_history = hist.history
loss = model_history['loss']

plt.figure()
plt.plot(loss, label='MSE')
plt.title('Mean Squared Error')
plt.show()

train_loss = hist.history['loss']

print("Error awal training:", train_loss[0])
print("Error akhir training:", train_loss[-1])

data_validasi = pd.read_excel('data_scaled_val.xlsx')

X_val = data_validasi[input_features]
y_val = data_validasi[output_features]

test_loss = model.evaluate(X_val, y_val, verbose=0)
print("Error testing (MSE):", test_loss)

predictions = model.predict(X_val)

plt.figure(figsize=(10,5))
plt.plot(y_val.values[:100], label='Aktual')
plt.plot(predictions[:100], label='Prediksi')
plt.xlabel('Index')
plt.ylabel('RR')
plt.title('Perbandingan Aktual vs Prediksi')
plt.legend()
plt.show()