# -*- coding: utf-8 -*-
"""Fix SVR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BNRCV4SDTMNcJQ2RzboUDniDAQt6lWdb
"""

# ---------------------------------------------------------
# 1. IMPORT LIBRARY
# ---------------------------------------------------------
import numpy as np
import pandas as pd
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.svm import SVR
from math import sqrt

from google.colab import files
import io
import matplotlib.pyplot as plt


# ---------------------------------------------------------
# 2. UPLOAD DATA (VERSI AMAN - TANPA KeyError)
# ---------------------------------------------------------
print("Upload data_training.xlsx, data_validasi.xlsx, data_testing.xlsx")
from google.colab import files
files.upload()

# baca langsung dari folder
df_train = pd.read_excel('data_training.xlsx')
df_val   = pd.read_excel('data_validasi.xlsx')
df_test  = pd.read_excel('data_testing.xlsx')

print("\nCek Data Training")
print(df_train.head())

# ---------------------------------------------------------
# 3. SPLIT INPUT (X) DAN OUTPUT (y)
# ---------------------------------------------------------
def split_xy(df):
    X = df.drop(["RR", "TANGGAL"], axis=1)
    y = df["RR"]
    return X, y

X_train, y_train = split_xy(df_train)
X_val, y_val     = split_xy(df_val)
X_test, y_test   = split_xy(df_test)


# ---------------------------------------------------------
# 4. SCALING (RobustScaler → lebih tahan outlier)
# ---------------------------------------------------------
scaler_X = RobustScaler()
scaler_y = RobustScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1,1)).ravel()

X_val_scaled = scaler_X.transform(X_val)
y_val_scaled = scaler_y.transform(y_val.values.reshape(-1,1)).ravel()

X_test_scaled = scaler_X.transform(X_test)
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1,1)).ravel()


# ---------------------------------------------------------
# 5. GRID SEARCH SVR (Anti Overfitting)
# ---------------------------------------------------------
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'gamma': ['scale', 0.001, 0.01],
    'epsilon': [0.01, 0.1, 0.2],
    'kernel': ['rbf']
}

tscv = TimeSeriesSplit(n_splits=5)

svr = SVR()

grid_search = GridSearchCV(
    svr,
    param_grid,
    scoring='neg_mean_squared_error',
    cv=tscv,
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train_scaled, y_train_scaled)

print("\nBest Parameters:", grid_search.best_params_)


# ---------------------------------------------------------
# 6. MODEL FINAL
# ---------------------------------------------------------
best_svr = grid_search.best_estimator_


# ---------------------------------------------------------
# 7. EVALUASI FUNCTION
# ---------------------------------------------------------
def evaluate(title, y_true, y_pred_scaled):
    y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1,1))
    rmse = sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    r2  = r2_score(y_true, y_pred)
    print(f"\n=== {title} ===")
    print("RMSE:", rmse)
    print("MAE :", mae)
    print("R²  :", r2)
    return rmse, mae, r2, y_pred


# ---------------------------------------------------------
# 8. PREDIKSI TRAIN, VAL, TEST
# ---------------------------------------------------------
train_pred_scaled = best_svr.predict(X_train_scaled)
val_pred_scaled   = best_svr.predict(X_val_scaled)
test_pred_scaled  = best_svr.predict(X_test_scaled)

rmse_train, mae_train, r2_train, train_pred = evaluate("TRAINING", y_train.values.reshape(-1,1), train_pred_scaled)
rmse_val, mae_val, r2_val, val_pred = evaluate("VALIDASI", y_val.values.reshape(-1,1), val_pred_scaled)
rmse_test, mae_test, r2_test, test_pred = evaluate("TESTING", y_test.values.reshape(-1,1), test_pred_scaled)


# ---------------------------------------------------------
# 9. GRAFIK PREDIKSI VS DATA ASLI (TEST)
# ---------------------------------------------------------
plt.figure(figsize=(10,5))
plt.plot(y_test.values, label='Data Asli', marker='o')
plt.plot(test_pred, label='Prediksi SVR', marker='x')
plt.title("Prediksi vs Data Asli (Testing)")
plt.xlabel("Index")
plt.ylabel("Curah Hujan (RR)")
plt.legend()
plt.grid()
plt.show()


# ---------------------------------------------------------
# 10. CONTOH PREDIKSI 1 DATA TEST
# ---------------------------------------------------------
contoh = X_test.iloc[0].values.reshape(1, -1)
contoh_scaled = scaler_X.transform(contoh)
hasil_pred_scaled = best_svr.predict(contoh_scaled)
hasil_pred = scaler_y.inverse_transform(hasil_pred_scaled.reshape(-1,1))

print("\nPrediksi 1 data test:", hasil_pred[0][0])