# -*- coding: utf-8 -*-
"""svm_curah_hujan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qcNByDIbl8Rw7_dh1w--nFlx0Mrh92Rm

1. Import Library
"""

import pandas as pd
import numpy as np

from google.colab import files

"""2. Pre-processing"""

# Ubah excel
df = pd.read_excel('data_mentah.xlsx')
df.to_csv('data_mentah.csv', index=False)

files.download('data_mentah.csv')

# Import data
df = pd.read_csv('data_mentah.csv')
df

# Melihat tipe data dari setiap atribut
df.info()

# Mengubah atribut object menjadi int supaya bisa diinterpolasi untuk mengisi nilai yang NaN
df['TN'] = pd.to_numeric(df['TN'], errors='coerce')
df['TX'] = pd.to_numeric(df['TX'], errors='coerce')
df['TAVG'] = pd.to_numeric(df['TAVG'], errors='coerce')
df['RR'] = pd.to_numeric(df['RR'], errors='coerce')
df['SS'] = pd.to_numeric(df['SS'], errors='coerce')

df.info()

# Melihat apakah ada missing value
df.isnull().sum()

# Menerapkan interpolasi untuk mengisi missing value
data_preprocessing = df.interpolate(method='linear')
data_preprocessing

# Melihat nilai duplikasi
data_preprocessing.duplicated().sum()

data_preprocessing.isnull().sum()

data_preprocessing[data_preprocessing.duplicated()]

data_preprocessing["TANGGAL"].value_counts()

data_preprocessing.duplicated(
    subset=["TANGGAL", "TN", "TX", "TAVG", "RH_AVG", "RR", "SS"]
).sum()

data_preprocessing[
    data_preprocessing['TANGGAL'] == '2021-03-06'
]

data_preprocessing = data_preprocessing.drop_duplicates()

data_preprocessing.duplicated().sum()

data_preprocessing

import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(data=data_preprocessing)
plt.xticks(rotation=45)
plt.show()

# Melihat jumlah data yang outlier
for col in df.select_dtypes(include=['float64', 'int64']).columns:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower) | (df[col] > upper)]
  print('Jumlah outlier', col, ':', len(outliers))

# Menghilangkan outlier pada tabel TN (Temperatur minimum)
Q1 = data_preprocessing["TN"].quantile(0.25)
Q3 = data_preprocessing["TN"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

data_preprocessing["TN"] = data_preprocessing["TN"].clip(lower, upper)

# Menghilangkan outlier untuk TX (Temperatur Maksimum)
Q1 = data_preprocessing['TX'].quantile(0.25)
Q3 = data_preprocessing['TX'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

data_preprocessing['TX'] = data_preprocessing['TX'].clip(lower, upper)

# Menghilangkan outlier untuk TAVG (Temperatur Rata-Rata)
Q1 = data_preprocessing['TAVG'].quantile(0.25)
Q3 = data_preprocessing['TAVG'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

data_preprocessing['TAVG'] = data_preprocessing['TAVG'].clip(upper, lower)

# Melihat hasil outlier
for col in data_preprocessing.select_dtypes(include=['float64', 'int64']).columns:
  Q1 = data_preprocessing[col].quantile(0.25)
  Q3 = data_preprocessing[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  outliers = data_preprocessing[(data_preprocessing[col] < lower) | (data_preprocessing[col] > upper)]
  print(col, 'Jumlah outlier: ', len(outliers))

# Memvisualisasikan untuk melihat outlier secara visual
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(data=data_preprocessing)
plt.xticks(rotation=45)
plt.show()

"""3. Analisis Statistik"""

data_preprocessing.describe()

"""4. Labelling data terlebih dahulu"""

bins = [-1, 5, 20, 50, 100, float('inf')]
labels = [
    'Sangat Ringan',
    'Ringan',
    'Sedang',
    'Lebat',
    'Sangat Lebat'
]

data_preprocessing['Kategori Hujan'] = pd.cut(
    data_preprocessing['RR'],
    bins=bins,
    labels=labels
)

data_preprocessing['Kategori Hujan'].value_counts()

data_preprocessing

data_preprocessing.to_csv('data_preprocessing.csv', index=False)

"""5. Encoding label atau target"""

# Mengubah label ke angka, karena metode SVM membutuhkan label numerik
label_map = {
    "Sangat Ringan": 0,
    "Ringan": 1,
    "Sedang": 2,
    "Lebat": 3,
    "Sangat Lebat": 4
}

data_preprocessing['Label'] = (
    data_preprocessing['Kategori Hujan'].map(label_map)
)

data_preprocessing

# Memeriksa apakah ada data yang gagal terlabel
data_preprocessing['Label'].isna().sum()

"""6. Splitting Data"""

from sklearn.model_selection import train_test_split

train_data, temp_data = train_test_split(
    data_preprocessing,
    test_size=0.2,
    shuffle=False
)

val_data, test_data = train_test_split(
    temp_data, test_size=0.5, shuffle=False
)

print("Data Training: ", len(train_data))
print("Data Validation: ", len(val_data))
print("Data Testing", len(test_data))

# Menyimpan data yang telah di split
train_data.to_csv("train_data.csv", index=False)
val_data.to_csv("val_data.csv", index=False)
test_data.to_csv("test_data.csv", index=False)

"""7. Scaling fitur"""

from sklearn.preprocessing import MinMaxScaler

features = ['TN', 'TX', 'TAVG', 'RH_AVG', 'SS']
scaler = MinMaxScaler()
# Fit hanya di data training
scaler.fit(train_data[features])

# Scaling data training
scaled_train = train_data.copy()
scaled_train[features] = scaler.transform(train_data[features])
scaled_train.to_csv('data_scaled_train.csv', index=False)

# Scaling data validation
scaled_val = val_data.copy()
scaled_val[features] = scaler.transform(val_data[features])
scaled_val.to_csv('data_scaled_val.csv', index=False)

# Scaling data testing
scaled_test = test_data.copy()
scaled_test[features] = scaler.transform(test_data[features])
scaled_test.to_csv('data_scaled_test.csv', index=False)

"""8. Memisahkan kolom X dan y"""

features = ['TN', 'TX', 'TAVG', 'RH_AVG', 'SS']
target = 'Label'

X_train = scaled_train[features]
y_train = scaled_train[target]

X_val = scaled_val[features]
y_val = scaled_val[target]

X_test = scaled_test[features]
y_test = scaled_test[target]

"""9. Training Data"""

# Buat model SVM
from sklearn.svm import SVC

svm_model = SVC(
    kernel = 'rbf',
    C = 100,
    gamma = 1,
    class_weight='balanced'
)

# Training model (fit)
svm_model.fit(X_train, y_train)

# Melihat akurasi training
from sklearn.metrics import accuracy_score, f1_score

y_train_pred = svm_model.predict(X_train)

train_accuracy = accuracy_score(y_train, y_train_pred)
print('Akurasi training:', train_accuracy)

# Melihat akurasi validasi
y_val_pred = svm_model.predict(X_val)

val_accuracy = accuracy_score(y_val, y_val_pred)
print('Akurasi Validasi:', val_accuracy)

C_values = [0.1, 1, 10, 100]
gamma_values = [0.01, 0.1, 1]

# Tuning parameter SVM (C and Gamma)
best_f1 = 0
best_param = None

for C in C_values:
    for gamma in gamma_values:
        model = SVC(
            kernel='rbf',
            C=C,
            gamma=gamma,
            class_weight='balanced'
        )
        model.fit(X_train, y_train)

        y_val_pred = model.predict(X_val)
        f1 = f1_score(y_val, y_val_pred, average='macro')

        if f1 > best_f1:
            best_f1 = f1
            best_param = (C, gamma)

print("Best F1-macro (Validation):", best_f1)
print("Best C, gamma:", best_param)

best_C, best_gamma = best_param

final_svm = SVC(
    kernel='rbf',
    C=best_C,
    gamma=best_gamma,
    class_weight='balanced'
)

final_svm.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_test_pred = final_svm.predict(X_test)

test_accuracy = accuracy_score(y_test, y_test_pred)
print("Akurasi Testing: ", test_accuracy)
print(classification_report(y_test, y_test_pred))

# Evaluasi Menggunakan Confusion Matrix

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

# hitung confusion matrix
cm = confusion_matrix(y_test, y_test_pred)

# nama kelas (sesuai label kamu)
class_names = [
    "Sangat Ringan",
    "Ringan",
    "Sedang",
    "Lebat",
    "Sangat Lebat"
]

# tampilkan grafik
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=class_names
)

disp.plot(cmap="Blues", xticks_rotation=45)
plt.title("Confusion Matrix SVM")
plt.show()